# Generated by Django 2.0 on 2017-12-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(max_length=30),
        ),
    ]
