# Generated by Django 2.0 on 2017-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreblog', '0002_auto_20171221_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_N',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_N',
            field=models.CharField(max_length=50),
        ),
    ]
