# Generated by Django 2.0 on 2017-12-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreblog', '0003_auto_20171221_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Image',
            field=models.ImageField(default='', upload_to='category_head_img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(default='', upload_to='post_head_img'),
        ),
    ]
