# Generated by Django 2.0 on 2017-12-30 16:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreblog', '0004_auto_20171221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
